version: '3.7'

services:
  bootnode:
    build:
      dockerfile: ./dockerfiles/miners/Dockerfile
      args:
        - ACCOUNT_PASSWORD=bootnode
    command: --nodekeyhex="ad125fb476cfcc57843e7ee650fc70942573883e66a3f3902b387993f83755ca" --nodiscover --ipcdisable --networkid=123454321 --netrestrict="172.16.254.0/28"
    container_name: bootnode
    hostname: bootnode
    networks:
      - eth-network
    

  alice:
    build:
      dockerfile: ./dockerfiles/miners/Dockerfile
      args:
        - ACCOUNT_PASSWORD=alice
    command: --bootnodes="enode://ab15e2bfbe7dcc525076f1763f030678d020eb7af6044f644cbb03d6d1095426fa39d10747dd2b7b9b40b89565964f48d4433aa00326495da78426937fce9bc4@bootnode:30303" --mine --miner.threads=1 --networkid=123454321 --netrestrict="172.16.254.0/28"
    container_name: alice
    hostname: alice
    networks:
      - eth-network

  bob:
    build:
      dockerfile: ./dockerfiles/miners/Dockerfile
      args:
        - ACCOUNT_PASSWORD=bob
    command: --bootnodes="enode://ab15e2bfbe7dcc525076f1763f030678d020eb7af6044f644cbb03d6d1095426fa39d10747dd2b7b9b40b89565964f48d4433aa00326495da78426937fce9bc4@bootnode:30303" --mine --miner.threads=1 --networkid=123454321 --netrestrict="172.16.254.0/28"
    container_name: bob
    hostname: bob
    networks:
      - eth-network

  carl:
    build:
      dockerfile: ./dockerfiles/miners/Dockerfile
      args:
        - ACCOUNT_PASSWORD=carl
    command: --bootnodes="enode://ab15e2bfbe7dcc525076f1763f030678d020eb7af6044f644cbb03d6d1095426fa39d10747dd2b7b9b40b89565964f48d4433aa00326495da78426937fce9bc4@bootnode:30303" --mine --miner.threads=1 --networkid=123454321 --netrestrict="172.16.254.0/28"
    container_name: carl
    hostname: carl
    networks:
      - eth-network

networks:
  eth-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.254.0/28